services:
  prodcataloguedb:
    container_name: prodcataloguedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ProdCatalogueDb
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - postgres_prodcataloguedb:/var/lib/postgresql/data